### ISSUE TITLE
Helping out

### ISSUE THREAD

**Issue by gcentauri** [anmoljagetia/leetcode-emacs-layer#1]
I'd like to help with this, but I don't have lots of free time.  I have never used leetcode, so i will take some time to set that up and try out your package. If you have specific questions, just let me know in this thread.

**Comment by anmoljagetia** [comment]
@gcentauri Thanks for helping out. Can you suggest how can I add custom keybindings, under `SPC a L`

basically, my thought follows that the ideal location for something like this will be Leader -> Applications -> Leetcode -> Functions?

**Comment by gcentauri** [comment]
@anmoljagetia sorry! i got super busy.  It makes sense to me that it would go under that heading, do you just need help with the elisp syntax for building a keymap?

**Comment by anmoljagetia** [comment]
Hey, I added the following code in keybindings.el and got them to work, so that's decent for now. I have two additional functionalities to add in mind. 

1. The ability to download the leetcode binary from the GitHub releases and add it to PATH.
2. So when I press `SPC a L` I see the heading as `prefix` whereas when I press `SPC a o` I see the heading `org-mode`. 

How can I get the label to change from "prefix" to "Leetcode"

**Comment by anmoljagetia** [comment]
Once again, really appreciate your effort in helping me and taking the time out for this. Please let me know if I can support/help you in anyway :)

**Comment by anmoljagetia** [comment]
@gcentauri Need some help

```elisp
(defvar leetcode--problems-mode-map
  (let ((map (make-sparse-keymap)))
    (prog1 map
      (suppress-keymap map)
      (define-key map (kbd "RET") #'leetcode-show-descri)
      (define-key map "n" #'next-line)
      (define-key map "p" #'previous-line)
      (define-key map "g" #'leetcode-problems-refresh)
      (define-key map "q" #'quit-window)))
  "Keymap for `leetcode--problems-mode'.")

(define-derived-mode leetcode--problems-mode
  tabulated-list-mode "LC Problems"
  "Major mode for browsing a list of problems."
  (setq tabulated-list-padding 2)
  (add-hook 'tabulated-list-revert-hook #'leetcode-problems-refresh nil t)
  :group 'leetcode)

(add-hook 'leetcode--problems-mode-hook #'hl-line-mode)

(defvar leetcode--problem-description-mode-map
  (let ((map (make-sparse-keymap)))
    (prog1 map
      (suppress-keymap map)
      (define-key map "n" #'next-line)
      (define-key map "p" #'previous-line)))
  "Keymap for `leetcode--problem-description-mode'.")

(define-derived-mode leetcode--problem-description-mode
  special-mode "LC Descri"
  "Major mode for display problem description."
  :group 'leetcode)
```

How do I set the following keybindings in spacemacs layer? Right now they are overshadowed by another mode (probably evil).

**Comment by gcentauri** [comment]
Its a bit hard to know out of context.  Is this a major mode you're defining to run some menu or something like that?  I don't use evil, but i know there are ways of integrating with other packages to make your keymap take precedence

**Comment by gcentauri** [comment]
For downloading a file, check out https://stackoverflow.com/questions/4448055/download-a-file-with-emacs-lisp  - You could also potentially make a system call to `curl` or `wget` or something.

For changing the `which-key` hint that just says `prefix`, check out this variable: `spacemacs/key-binding-prefixes`.  which is defined in `.emacs.d/layers/+spacemacs/spacemacs-defaults`/keybindings.el

**Comment by anmoljagetia** [comment]
@gcentauri Thanks a lot for the resources. Turns out it was only one line.

```elisp
(spacemacs/declare-prefix "a L" "Leetcode")
```

I now can't seem to make my key-map take precedence over some of the other modes that are clashing.

**Comment by anmoljagetia** [comment]
```elisp

;;(spacemacs/set-leader-keys-for-major-mode 'leetcode--problems-mode "H SPC" 'leetcode-show-descri)
;;(spacemacs/set-leader-keys-for-major-mode 'problems-mode "H SPC" 'leetcode-show-descri)

;;(with-eval-after-load 'leetcode--problems-mode
;;  (define-key leetcode--problems-mode-map (kbd "H-SPC") #'leetcode-show-descri))

;;(eval-after-load 'leetcode--problems-mode `(evil-define-key 'leetcode--problems-mode-map "RET" 'leetcode-show-descri))

;;(define-key leetcode--problems-mode (kbd "RET") 'leetcode-show-descri)
;;(define-key leetcode--problems-mode-map (kbd "RET") 'leetcode-show-descri)

;;(define-key leetcode--problems-mode  "RET" 'leetcode-show-descri)
;;(define-key leetcode--problems-mode-map "RET" 'leetcode-show-descri)

(add-hook 'leetcode--problems-mode-hook
          (lambda ()
            (local-set-key "H-SPC" #'leetcode-show-descri)))
```

I have tried all the above methods, but to no avail. The code that I am pointing at at the moment, is available at : https://github.com/kaiwk/leetcode.el/blob/master/leetcode.el#L742-L760

What am I doing wrong here? I can't seem to figure this out.

The error that I am getting is : 

```
RET             leetcode-show-descri
  (that binding is currently shadowed by another mode)
```
This is when I press `C-h m`

**Comment by gcentauri** [comment]
What are you trying to accomplish here?  It looks like you want `H-SPC` (is that the hyper key?) to launch the `leetcode-show-descri` function right?  As far as I can tell, all those keybindings should be already available to you when you are in `leetcode-mode`.  Now, if `evil` is clobbering some of them, you might need to figure out how to deal with that.  I don't use `evil` but I do use a different modal key map.  I had to configure a hook to put me into `insert` mode (just normal emacs keys) whenever I opened a `magit` buffer.  So it might be simple as:

`(add-hook 'leetcode--problems-mode-hook 'evil-insert)` to make sure you're in the right mode whenever you activate the `leetcode--problems-mode` or whatever it is called.

**Comment by anmoljagetia** [comment]
What I want to accomplish is : 

When the buffer is populated with rows of leetcode problems, when I press the return key, it should call the function `leetcode-show-descri`.

Right now, one of the other modes are clashing with it, and all I see is the cursor move to the next line. I want to override all the other minor modes or however those keys are crashing and call the `leetcode-show-descri` on the row so that it can perform the desired output.

**Comment by anmoljagetia** [comment]
So, on further debugging, I have been able to narrow it down further and have been able to reduce it to the following case: 

``` elisp
(defun myleetcode2/init-leetcode ()
  (use-package leetcode
    :config
    (setq
     leetcode-account "gakc"
     leetcode-password "qwedsa@123")
      (define-key leetcode--problems-mode-map (kbd "C-SPC") 'leetcode-show-descri)
    ))
```
^ This works as intended.

Now when I change the last line to be : 

```elisp
(define-key leetcode--problems-mode-map (kbd "return") 'leetcode-show-descri)
```
or 
``` elisp
(define-key leetcode--problems-mode-map "return" 'leetcode-show-descri)
```
 it doesn't work as intended which is that the function should be called when the "Return" key is pressed alone. How can I achieve that?

**Comment by gcentauri** [comment]
try `(kbd "RET")`

**Comment by anmoljagetia** [comment]
`(kbd "RET")` didn't work.
It still takes me to the next line, which is also the same behavior in vim, so I think it is probably evil that's messing with this keybinding. Not sure how to force emacs to use RET as what I want to do at the moment.

**Comment by anmoljagetia** [comment]
Running describe-key gives me the following docs :

```
RET (translated from <return>) runs the command evil-ret (found in
evil-motion-state-map), which is an interactive compiled Lisp function in
‘evil-commands.el’.

It is bound to RET.

(evil-ret &optional COUNT)

Move the cursor COUNT lines down.
If point is on a widget or a button, click on it.
In Insert state, insert a newline.
```

**Comment by anmoljagetia** [comment]
So, I think I figured what works!
It's adding `(kbd "<return>")` to the mix of lines.

**Comment by anmoljagetia** [comment]
Thanks a lot! You're an absolute gem of a human! 🎉

**Comment by gcentauri** [comment]
Thanks!  I'm glad to help.  The Free Software community helped me get where I am today and I enjoy giving back.

I'm curious why the final `(kbd "<return>")` worked.  You can use `describe-bindings` (`SPC h d b`) to see what keys are bound in current modes and for which keymap.  But seems like you got your bindings active for the leetcode mode now?

**Comment by gcentauri** [comment]
seems like this is "resolved"? I guess I never go to your last question :0  I'll go ahead and close it, just cleaning up after myself :)
