### ISSUE TITLE
REQUEST [error] after login in successfully

### ISSUE THREAD

**Issue by Voleking** [anmoljagetia/leetcode-emacs-layer#4]
When I login in successfully, and run M-x Leetcode another time, I got this error: 
```
REQUEST [error] Error (error) while connecting to https://leetcode.com/api/problems/all/.
deferred error : (wrong-type-argument number-or-marker-p nil)
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 58d5bb920)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by anmoljagetia** [comment]
This works for me. Are you sure that you put in your password/username correctly?

**Comment by Voleking** [comment]
@anmoljagetia Yes, I try to delete .authinfo and `M-x leetcode` again, the content of .authinfo looks like below and I confirm all this info is correct.
```
machine leetcode.com login $username password *******
```
I tried to reinstall the layer, but the issue is still there.

**Comment by Voleking** [comment]
I think it's kaiwk/leetcode.el issue, I will report there.

**Comment by Voleking** [comment]
fix upstream, close it. BTW, thx you layer!
